const assert = require('assert')
const {generateNextTag} = require('../src/modules/versioning')

assert.strictEqual(generateNextTag('major', '', 'semver'), '1.0.0')
assert.strictEqual(generateNextTag('major', '2.1.78', 'semver'), '3.0.0')
assert.strictEqual(generateNextTag('minor', '', 'semver'), '0.1.0')
assert.strictEqual(generateNextTag('minor', '2.1.78', 'semver'), '2.2.0')
assert.strictEqual(generateNextTag('patch', '', 'semver'), '0.0.1')
assert.strictEqual(generateNextTag('patch', '2.1.78', 'semver'), '2.1.79')
assert.strictEqual(generateNextTag('premajor.dev', '', 'semver'), '1.0.0-dev.0')
assert.strictEqual(generateNextTag('premajor.dev', '2.1.78', 'semver'), '3.0.0-dev.0')
assert.strictEqual(generateNextTag('premajor.dev', '2.1.78-dev.29', 'semver'), '3.0.0-dev.0')
assert.strictEqual(generateNextTag('preminor.dev', '', 'semver'), '0.1.0-dev.0')
assert.strictEqual(generateNextTag('preminor.dev', '2.1.78', 'semver'), '2.2.0-dev.0')
assert.strictEqual(generateNextTag('preminor.dev', '2.1.78-dev.29', 'semver'), '2.2.0-dev.0')
assert.strictEqual(generateNextTag('prepatch.dev', '', 'semver'), '0.0.1-dev.0')
assert.strictEqual(generateNextTag('prepatch.dev', '2.1.78', 'semver'), '2.1.79-dev.0')
assert.strictEqual(generateNextTag('prepatch.dev', '2.1.78-dev.29', 'semver'), '2.1.79-dev.0')
assert.strictEqual(generateNextTag('dev', '', 'semver'), '0.0.1-dev.0')
assert.strictEqual(generateNextTag('dev', '2.1.78', 'semver'), '2.1.79-dev.0')
assert.strictEqual(generateNextTag('dev', '2.1.78-dev.29', 'semver'), '2.1.78-dev.30')
assert.strictEqual(generateNextTag('alpha', '', 'semver'), '0.0.1-alpha.0')
assert.strictEqual(generateNextTag('alpha', '2.1.78', 'semver'), '2.1.79-alpha.0')
assert.strictEqual(generateNextTag('alpha', '2.1.78-alpha.29', 'semver'), '2.1.78-alpha.30')
assert.strictEqual(generateNextTag('beta', '', 'semver'), '0.0.1-beta.0')
assert.strictEqual(generateNextTag('beta', '2.1.78', 'semver'), '2.1.79-beta.0')
assert.strictEqual(generateNextTag('beta', '2.1.78-beta.29', 'semver'), '2.1.78-beta.30')
assert.strictEqual(generateNextTag('rc', '', 'semver'), '0.0.1-rc.0')
assert.strictEqual(generateNextTag('rc', '2.1.78', 'semver'), '2.1.79-rc.0')
assert.strictEqual(generateNextTag('rc', '2.1.78-rc.29', 'semver'), '2.1.78-rc.30')

const date = new Date(Date.now())
const year = date.getUTCFullYear().toString()
const month = (date.getUTCMonth() + 1).toString()
assert.strictEqual(generateNextTag('major', '', 'calver', 'yyyy.mm.major'), '0.0.1')
assert.strictEqual(generateNextTag('major', '2021.11.7', 'calver', 'yyyy.mm.major'), '2021.11.8')
assert.strictEqual(generateNextTag('minor', '', 'calver', 'yyyy.mm.major.minor'), `0.0.0.1`)
assert.strictEqual(generateNextTag('calendar', '', 'calver', 'yyyy.mm.major.minor'), `${year}.${month}.0.0`)
